baseurl = "https://www.semidocumentedlife.com/"
title = "semi documented life"
author = "Andrew Moore"
canonifyurls = true
languagecode = "en"
theme = "hugo-black-and-light-theme"
publishDir = "public/"

googleAnalytics = "UA-108115849-1"

pygmentsstyle       = "bw"
pygmentscodefences  = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "semi documented life"

[[menu.main]]
    name = "about"
    url  = "about"
[[menu.main]]
    name = "github"
    url  = "https://github.com/mooreaw/"
[[menu.main]]
    name = "twitter"
    url  = "https://twitter.com/theysayHeyDrew/"
[[menu.main]]
    name = "cv"
    url  = "https://github.com/mooreaw/cv/"
