baseurl = "https://www.semidocumentedlife.com/"
title = "semi documented life"
author = "Andrew Moore"
languageCode = "en"
theme = "kiss"
publishDir = "public/"
googleAnalytics = "UA-108115849-1"

enableRobotsTXT = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "mooreaw_"
github = "mooreaw"
email = "moore.andrew09@gmail.com"
instagram = "amateurthoughts"

[blackfriday]
hrefTargetBlank = true

[params.sections_right]
"/about/" = "about"
"https://github.com/mooreaw/cv/" = "cv"
