baseurl = "https://www.ndrewwm.com/"
title = "andrew w. moore // blog"
author = "Andrew Moore"
languageCode = "en"
theme = "kiss"
publishDir = "public/"

enableRobotsTXT = true

# pygmentsCodeFences = true
# pygmentsStyle = "tango"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "ndrewwm"
github = "ndrewwm"
email = "hello@ndrewwm.com"
# instagram = "amateurthoughts"
linkedin = "ndrewwm"

[blackfriday]
hrefTargetBlank = true

[params.sections_right]
"/about/" = "about"
"/now/" = "now"
"/cv/" = "cv"
"/blog/" = "blog"
